config/routes.rb
Hackerboard::Application.routes.draw do
  root :to => "questions#index"

  namespace :admin do
    resources :categories do
      # member do
      #   get :remove
      # end

      get :remove, :on => :member
    end
  end

  controller :search do
    get "/search", :action => :questions, :as => :search
  end

  controller :sessions do
    get "/login", :action => :new
    post "/login", :action => :create
    get "/logout", :action => :destroy
  end

  controller :users do
    get "/signup", :action => :new
    post "/signup", :action => :create
    get "/users/:id", :action => :show, :as => :profile
  end

  controller :questions do
    get "/questions/feed", :action => :feed, :as => :questions_feed
    get "/questions/:id", :action => :show, :as => :question, :id => /\d+/
    get "/questions/new", :action => :new, :as => :new_question
    post "/questions/new", :action => :create, :as => false
    get "/questions", :action => :index, :as => :questions
  end

  post "/questions/:question_id/comments/new", :to => "comments#create", :as => :new_comment

  get "/dashboard", :to => "dashboard#index", :as => :dashboard
  get "/categories/:id", :to => "categories#show", :as => :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :questions, :dependent => :destroy

  validates_presence_of :name

  scope :sorted, order("name asc")
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body
  attr_readonly :user_id, :question_id

  belongs_to :user
  belongs_to :question, :counter_cache => true

  validates_presence_of :body, :user, :question
end

app/models/filtered_question.rb
class FilteredQuestion
  attr_accessor :params

  def self.filter(params)
    new(params).filter
  end

  def initialize(params)
    @params = params
  end

  def filter
    scope = Question.paginate(params[:page]).recent
    scope = scope.unanswered if params[:filter] == "unanswered"
    scope
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :body, :category_id
  attr_readonly :user_id

  belongs_to :user
  belongs_to :category, :counter_cache => true
  has_many :comments

  validates_presence_of :title, :body, :user, :category

  scope :unanswered, where(:comments_count => 0)
  scope :recent, order("id desc")
  scope :feed, limit(10).order("id desc").includes(:category)

  define_index do
    indexes title
    indexes body
  end

  def viewed!
    increment!(:views_count)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  attr_reader :password

  validates_presence_of :name
  validates_format_of :email, :with => /@/
  validates_presence_of :password, :if => :require_password?
  validates_confirmation_of :password, :if => :require_password?
  validates_uniqueness_of :email

  has_many :questions
  has_many :comments

  scope :recent, order("id desc").limit(10)

  # def self.recent
  #   order("id desc").limit(10)
  # end

  def password=(password)
    salt, hash = PasswordEncryptor.encrypt(password)
    self.password_salt = salt
    self.password_hash = hash
    @password = password
  end

  private
  def require_password?
    new_record? || password.present? || password_confirmation.present?
  end
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < ApplicationController
    respond_to :html

    http_basic_authenticate_with :name => "admin", :password => "admin", :realm => "Hackerboard Admin"

    before_filter :find_category, :only => [:edit, :update, :remove, :destroy]

    def index
      @categories = Category.scoped
    end

    def edit
    end

    def update
      @category.update_attributes(params[:category])
      respond_with(@category, :location => admin_categories_path)
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.create(params[:category])
      respond_with(@category, :location => admin_categories_path)
    end

    def remove
    end

    def destroy
      @category.destroy
      respond_with(@category, :location => admin_categories_path)
    end

    private
    def find_category
      @category = Category.find(params[:id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :logged_in?
  self.responder = ApplicationResponder

  private
  def self.require_logged_user(options = {})
    before_filter options do
      redirect_to login_path, :alert => t("flash.require_login") unless logged_in?
    end
  end

  def logged_in?
    current_user.present?
  end

  def current_user
    # @current_user ||= session[:user_id] && User.find(session[:user_id])
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @question_list = CategoryQuestionList.new(@category, params)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  require_logged_user

  def create
    @question = Question.find(params[:question_id])
    @comment = @question.comments.new(params[:comment])
    @comment.user = current_user

    if @comment.save
      flash[:notice] = t("flash.comment.create")
    else
      flash[:alert] = t("flash.comment.fail")
    end

    redirect_to question_path(@question)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  require_logged_user :only => [:new, :create]
  before_filter :find_categories, :only => [:new, :create]

  def index
    @question_list = QuestionList.new(FilteredQuestion.filter(params))
  end

  def feed
    @questions = Question.feed

    respond_to do |format|
      format.xml# { render :xml => @questions }
      format.json { render :json => @questions }
    end
  end

  def show
    @question = Question.find(params[:id])
    @question.viewed!
    @comments = @question.comments.includes(:user)
    @comment_form = CommentForm.new(@question, logged_in?)
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(params[:question])

    if @question.save
      redirect_to question_path(@question), :notice => t("flash.question.create")
    else
      render :new
    end
  end

  private
  def find_categories
    @categories = Category.sorted
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  rescue_from Riddle::ConnectionError do
    render :text => "Search is down. :("
  end

  def questions
    @questions = Question.search(params[:query], :page => params[:page], :per_page => 3)
    render :default
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "window"

  def new
  end

  def create
    user = Authenticator.authenticate(params[:email], params[:password])

    if user
      reset_session
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      flash.now[:alert] = t("flash.login.fail")
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "window"

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    render :layout => "application"
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      Mailer.welcome({
        :name => @user.name,
        :email => @user.email,
        :url => login_url
      }).deliver

      flash.notice = t("flash.user.create")
      redirect_to login_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hint(object, attribute)
    scope = ["hints", object.class.name.underscore, attribute].join(".")
    translation = t(scope, :default => "")

    return if translation.blank?
    content_tag(:span, translation, :class => "hint")
  end

  def gravatar(email)
    email_hash = Digest::MD5.hexdigest(email)
    image_tag "http://www.gravatar.com/avatar/#{email_hash}?s=25&d=mm", :alt => ""
  end

  def profile_link(user)
    render "shared/profile_link", :user => user
  end
end

app/views/admin/categories/_category.html.erb
<p>
  <%= category.name %>
  <%= link_to t("category.edit"), edit_admin_category_path(category) %>
  <%= link_to t("category.remove"), remove_admin_category_path(category) %>
</p>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, category] do |f| %>
  <%= render "shared/error_messages", :record => category %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
  </p>
<% end %>

app/views/admin/categories/edit.html.erb
<%= render "form", :category => @category %>

app/views/admin/categories/index.html.erb
<p>
  <%= link_to t("category.add_category"), new_admin_category_path %>
</p>

<%= render @categories %>

app/views/admin/categories/new.html.erb
<%= render "form", :category => @category %>

app/views/admin/categories/remove.html.erb
<%= form_for [:admin, @category], :method => :delete do |f| %>
  <p>
    <%= t("category.are_you_sure_you_want_to_remove_html", :category => @category.name) %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<%= render @question_list.to_partial, :questions => @question_list.questions %>

<% content_for :sidebar do %>
  <%= render "shared/search" %>
  <%= render "shared/categories", :categories => @question_list.categories %>
<% end %>

app/views/comments/_comment.html.erb
<div class="comment">
  <p class="profile">
    <%= profile_link(comment.user) %>
    <%= t("addr.commented_this", :time => time_ago_in_words(comment.created_at)) %>
  </p>

  <%= simple_format comment.body %>
</div>

app/views/comments/_form.html.erb
<%= form_for Comment.new, :url => new_comment_path(question) do |f| %>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/_require_login.html.erb
<p>
  Faça seu login para comentar
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackerboard</title>
  <%= javascript_include_tag "modernizr" %>
  <%= stylesheet_link_tag "shared", "hb" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="page">
    <%= render "shared/header" %>
    <%= render "shared/flash_messages" %>

    <div class="content container group">
      <section class="main">
        <%= yield %>
      </section>

      <aside class="sidebar">
        <%= yield :sidebar %>
      </aside>
    </div>

    <footer class="container">
      <nav>
        <ul>
          <li><%= link_to t("nav.signup"), signup_path %></li>
          <li><%= link_to t("nav.login"), login_path %></li>
        </ul>
      </nav>
    </footer>
  </div>
</body>
</html>

app/views/layouts/window.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackerboard</title>
  <%= javascript_include_tag "modernizr" %>
  <%= stylesheet_link_tag "shared", "hb", "window" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="page">
    <%= render "shared/header" %>
    <%= render "shared/flash_messages" %>

    <div class="content container group">
      <section class="main">
        <%= yield %>
      </section>

      <aside class="sidebar">
        <%= yield :sidebar %>
      </aside>
    </div>

    <footer class="container">
      <nav>
        <ul>
          <li class="hellobits"><a href="http://hellobits.com/">Hellobits</a></li>
          <li><%= link_to t("nav.signup"), signup_path %></li>
          <li><%= link_to t("nav.login"), login_path %></li>
        </ul>
      </nav>
    </footer>
  </div>
</body>
</html>

app/views/questions/_no_questions.html.erb
<p>
  <%= t("question.no_questions_found") %>
</p>

app/views/questions/_question.html.erb
<article class="post">
  <h2><%= link_to question.title, question_path(question) %></h2>
  <ul class="meta">
    <li>
      <%= profile_link(question.user) %>
    </li>

    <li class="published-at">
      <%= t("question.published_at", :time => time_ago_in_words(question.created_at)) %>
    </li>

    <li class="icon view">
      <%= t("question.views_html", :count => question.views_count) %>
    </li>

    <li class="icon comment">
      <%= t("question.comments_html", :count => question.comments_count) %>
    </li>
  </ul>
</article>

app/views/questions/_questions.html.erb
<% iterate questions do |question| %>
  <%= render question %>
<% end %>

<%= paginate questions %>

app/views/questions/index.html.erb
<h1>Latest posts</h1>

<dl class="filters">
  <dt>Filter posts</dt>

  <dd><%= link_to t("question.all"), questions_path %></dd>
  <dd><%= link_to t("question.unanswered"), questions_path(:filter => "unanswered") %></dd>
</dl>

<%= render @question_list.to_partial, :questions => @question_list.questions %>

<% content_for :sidebar do %>
  <%= render "shared/search" %>
  <%= render "shared/categories", :categories => @question_list.categories %>
  <%= render "shared/users", :users => @question_list.users %>
<% end %>

app/views/questions/new.html.erb
<%= form_for @question, :url => new_question_path do |f| %>
  <%= render "shared/error_messages", :record => @question %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, @categories, :id, :name, :include_blank => true %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/questions/show.html.erb
<article>
  <h1><%= @question.title %></h1>
  <%= simple_format @question.body %>

  <p class="profile">
    <%= profile_link(@question.user) %>
    <%= t("question.published_this", :time => l(@question.created_at, :format => :short)) %>
  </p>
</article>

<h2><%= t("comment.title") %></h2>

<%= render @comments %>
<%= render *@comment_form.to_partial %>

<% content_for :sidebar do %>
  <h3><%= t("question.about") %></h3>
  <ul class="stats">
    <li>
      <%= t("question.views_html", :count => @question.views_count) %>
    </li>

    <li>
      <%= t("question.comments_html", :count => @question.comments_count) %>
    </li>

    <li>
      <%= link_to "RSS", questions_feed_path(:format => "xml"), :class => "feed" %>
    </li>
  </ul>

  <%= render "shared/search" %>
  <%= render "shared/categories", :categories => Category.all %>
<% end %>

app/views/search/default.html.erb
<% iterate @questions do |question| %>
  <%= render question %>
<% end %>

<%= paginate @questions %>

app/views/shared/_categories.html.erb
<h1>Categories</h1>
<ul class="categories">
  <% categories.each do |category| %>
    <li>
      <%= link_to category.name, category_path(category) %>
      <strong><%= t("category.questions_html", :count => category.questions_count) %></strong>
    </li>
  <% end %>
</ul>

app/views/shared/_error_messages.html.erb
<% if record.errors.any? %>
  <dl class="error-messages">
    <dt><%= t("errors.double_check_your_form") %></dt>

    <% record.errors.full_messages.each do |message| %>
      <dd><%= message %></dd>
    <% end %>
  </dl>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, value| %>
  <p class="message <%= name %>">
    <%= value %>
  </p>
<% end %>

app/views/shared/_header.html.erb
<header class="main container">
  <%= link_to image_tag("hackerboard.png"), root_path %>

  <nav>
    <ul>
      <li class="home"><%= link_to t("nav.home"), root_path %></li>
      <li class="new-question"><%= link_to t("nav.new_question"), new_question_path %></li>

      <% if logged_in? %>
        <li class="logout">
          <%= t("greetings.hello", :name => current_user.name) %> |
          <%= link_to t("nav.logout"), logout_path %>
        </li>
      <% else %>
        <li class="login"><%= link_to t("nav.login"), login_path %></li>

        <li class="signup">
          <%= link_to t("nav.signup"), signup_path, :class => "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/shared/_profile_link.html.erb
<a class="avatar" href="<%= profile_path(user) %>">
  <%= gravatar user.email %>
  <span class="user"><%= user.name %></span>
</a>

app/views/shared/_search.html.erb
<h1><%= t("search.search") %></h1>

<%= form_tag search_path, :method => :get, :class => "search" do %>
  <p>
    <%= search_field_tag :query, nil, :placeholder => t("search.placeholder") %>
    <%= submit_tag t("search.ok") %>
  </p>
<% end %>

app/views/shared/_users.html.erb
<h1><%= t("greetings.welcome_aboard") %></h1>
<ul class="users">
  <% users.each do |user| %>
    <li>
      <%= profile_link(user) %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= form_for @user, :url => signup_path do |f| %>
  <%= render "shared/error_messages", :record => @user %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= hint(@user, :name) %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= hint(@user, :email) %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>